version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - npm install 
    build:
        commands:
            - npm run-script build
artifacts:
  files:
  - ./*
  - ./**/**
  # React directory
  # base-directory: build
  
  # Vue directory
  base-directory: dist